<?php

namespace Store\RestBundle\Repository;
use Doctrine\ORM\EntityManager;
use Store\RestBundle\Entity\Articulos;
use Store\RestBundle\Entity\Clientes;

/**
 * ArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientesRepository extends RestBaseRepository
{

    private function getPrecios(Clientes $entity)
    {

        $res= $this->getEntityManager()->getRepository('StoreRestBundle:FormasPagos')->find($entity->getIdFormaPago());
        $entity->setFormaPagoObject($res);
		  $entity->sett_re(0);
		if($this->data!=null)
        if($entity->getRecargoEquivalencia()==true)
        {
	
            $s = $this->data['store']->getRepository('CommonAdminBaseBundle:Options')->findBy(array('name'=>'Recargo'));
			if(count($s)>0)
			{
            $s =$s[0]->getValueData('default');
            $entity->sett_re($s);
        }}
			
    }
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        $t = parent::findBy($criteria, $orderBy, $limit, $offset);
        foreach($t as $t1)
            $this->getPrecios($t1);
        return $t;
    }
    public function find($id)
    {
        $t = parent::find($id);
        if($t!=null)
            $this->getPrecios($t);
        return $t;
    }
    public function findAll()
    {

        $t = parent::findAll();
        foreach($t as $t1)
            $this->getPrecios($t1);
        return $t;

    }
}
