<?php

namespace Store\RestBundle\Repository;
use Doctrine\ORM\EntityManager;

/**
 * RestBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestBaseRepository extends \Doctrine\ORM\EntityRepository
{
    protected $data;


    public function setData($array)
    {
        $this->data =$array;
        return $this;
    }

}
